echo # Bloqueo de toda la telemetría de Windows
echo 127.0.0.1    vortex.data.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    vortex-win.data.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    telecommand.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    telecommand.telemetry.microsoft.com.nsatc.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    oca.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    oca.telemetry.microsoft.com.nsatc.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    sqm.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    sqm.telemetry.microsoft.com.nsatc.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    watson.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    watson.telemetry.microsoft.com.nsatc.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    redir.metaservices.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    choice.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    choice.microsoft.com.nsatc.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    df.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    reports.wes.df.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    wes.df.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    services.wes.df.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    sqm.df.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    watson.ppe.telemetry.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    telemetry.appex.bing.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    telemetry.urs.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    settings-sandbox.data.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    vortex-sandbox.data.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    survey.watson.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    watson.live.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    watson.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    statsfe2.ws.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    corpext.msitadfs.glbdns2.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    compatexchange.cloudapp.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    cs1.wpc.v0cdn.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    a-0001.a-msedge.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    statsfe2.update.microsoft.com.akadns.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    sls.update.microsoft.com.akadns.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    fe2.update.microsoft.com.akadns.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    diagnostics.support.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    corp.sts.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    statsfe1.ws.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    pre.footprintpredict.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    i1.services.social.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    i1.services.social.microsoft.com.nsatc.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    feedback.windows.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    feedback.microsoft-hohm.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    feedback.search.microsoft.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    rad.msn.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    preview.msn.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    ad.doubleclick.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    ads.msn.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    ads1.msads.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    ads1.msn.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    a.ads1.msn.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    a.ads2.msn.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    adnexus.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    adnxs.com >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    az361816.vo.msecnd.net >> C:\Windows\System32\drivers\etc\hosts
echo 127.0.0.1    az512334.vo.msecnd.net >> C:\Windows\System32\drivers\etc\hosts
